### ISSUE TITLE
Latexmk: Rule 'lualatex' became out-of-date?

### ISSUE THREAD

**Issue by alexg-k** [mrkline/latex-book#2]
My Latexmk version is: Latexmk, John Collins, 25 October 2018. Version 4.61

Invoking latexmk like stated in the README:
`latexmk -lualatex -latexoption=-halt-on-error main.tex`

I get the following response:
`Rule 'lualatex': The following rules & subrules became out-of-date:
      'lualatex'`

For now I went with '-pdflua', though I am aware these options are not the same.

**Comment by ericrbg** [comment]
erm, what was your solution to this?

**Comment by mrkline** [comment]
AFAIK, `latexmk` just prints that to indicate that it needs to run LuaLaTeX (as opposed to the PDF being up to date).  After running `latexmk -c` to clean up the repo, I see
```
$ latexmk -lualatex -latexoption=-halt-on-error modern-latex.tex
Rc files read:
  NONE
Latexmk: This is Latexmk, John Collins, 17 Apr. 2020, version: 4.69a.
Latexmk: applying rule 'lualatex'...
Rule 'lualatex': The following rules & subrules became out-of-date:
      'lualatex'
------------
Run number 1 of rule 'lualatex'
------------
------------
Running 'lualatex  -halt-on-error -recorder  "modern-latex.tex"'
------------

< several runs here>

Latexmk: References changed.
Latexmk: Log file says output to 'modern-latex.pdf'
Latexmk: All targets (modern-latex.pdf) are up-to-date
```

After this successful run, the same command prints
```
$ latexmk -lualatex -latexoption=-halt-on-error modern-latex.tex
Rc files read:
  NONE
Latexmk: This is Latexmk, John Collins, 17 Apr. 2020, version: 4.69a.
Latexmk: All targets (modern-latex.pdf) are up-to-date
```

Are you having some issue where LuaLaTeX doesn't typeset the book after you see that?
