### ISSUE TITLE
"GaramondPremierPro" cannot be found

### ISSUE THREAD

**Issue by sierxue** [mrkline/latex-book#3]
My system is Ubuntu 18.04 with texlive 2019 fully installed.

When I compiled with the way recommended in README, I got the following message: 

> Package fontspec Error: The font "GaramondPremierPro" cannot be found.

**Comment by mrkline** [comment]
I'm typesetting the book with [Garamond Premier](https://fonts.adobe.com/fonts/garamond-premier). Assuming you don't have a copy, you'll need to change the fonts to ones you have (see the `\setmainfont`, `\setsansfont`, and `\setmonofont` commands).
